services:
  layer7-ddos-guard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
      container_name: layer7-ddos-guard
      ports:
        - 5000:5000
      depends_on:
        - redis

  redis:
    image: redis:alpine
