services:
  pow-guard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: pow-guard
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis:alpine

networks:
  default:
    external:
      name: docker-network