services:
  layer7-ddos-guard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: layer7-ddos-guard
    depends_on:
      - redis

  redis:
    image: redis:alpine

networks:
  default:
    external:
      name: docker-network