FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /code

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    PATH="/code/.venv/bin:$PATH"

COPY ./pyproject.toml ./uv.lock ./
RUN uv sync --frozen --no-dev

COPY .env ./
COPY ./mockserver ./mockserver

CMD ["uvicorn", "mockserver:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
