services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    container_name: devcontainer
    volumes:
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      - ..:/home/workspace
    stdin_open: true
    depends_on:
      - app
      - redis
      - mockserver

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: layer7-ddos-guard
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis:alpine

  mockserver:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.mockserver
    container_name: mockserver
    ports:
      - 5001:5001
    depends_on:
      - app
