FROM python:3.13-slim 

RUN pip install pipenv

WORKDIR /code 

COPY ./Pipfile ./Pipfile.lock ./
RUN pipenv install --system --deploy

COPY .env ./
COPY ./mockserver ./mockserver

CMD ["uvicorn", "mockserver:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]